---
title: "README"
format: gfm
---

For this assignment, I want you to *plot* something. You can use data of your own, some sample data we've worked with, or interesting data that's freely available online. Some sources to explore for interesting datasets might be:

-   The `{gapminder}` R package <https://github.com/jennybc/gapminder>

-   The `{hockeystick}` R package <https://cortinah.github.io/hockeystick/>

-   The `{bakeoff}` R package <https://bakeoff.netlify.app/>

FiveThirtyEight also has a number of datasets available that they used for their stories. You can browse a list here: <https://data.fivethirtyeight.com/>. Most link to a github repository if you click on info.

## When you should get started:

ASAP. There is one office hours session between now and when the project is due. That session + email correspondences is the time we have to work out any issues together. I cannot promise to be able to respond on an emergency time frame the day or evening before this is due.

## What you should do:

Follow best practices as you've learned in the class to produce and fine tune a data visualization.

## What you should tell me:

Here are some kinds of things you should tell me about your process (this isn't a checklist):

-   What data you're plotting, and what its source is.

-   Are there any sources of inspiration you're pulling from?

-   Do you have a sketch of what you'd *like* the plot to look like?

-   What *decisions* did you make in creating the plot (e.g. labels, colors, geometries, plot orientation, etc.)

-   Why did you make those decisions?

-   Does the final plot fall short of your ultimate vision in any way?

## How to use github

I won't grade anything until you've told me that the project is submitted through the canvas submission. Therefore, commit and push to Github regularly. The best way to ask for help will be to reference files and lines that are on github.

## What to submit:

Draft your report and visualization code in `vizualization_final_report.qmd`. Once you've made your final commit and pushed it to github, submit a "Project submitted" message on canvas.
